apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Calling productpage..."
              curl -sS productpage:9080/productpage > /dev/null 2>&1 || true
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Request completed"
              sleep 2
            done
      restartPolicy: Always
